name: CI

on:
  #schedule:
  #  - cron: '0 0 * * 0' #Once a week at 00:00 on Sunday
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: read
  packages: write


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  Base:
    name: Docker Image - BASE - ${{ matrix.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['8.3']

    steps:
      # —— Setup Environment actions  ——————————————————————————————————————————————

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # —— Build base image  ——————————————————————————————————————————————
      - name: Build and push - PHP Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: php-fpm-alpine-base
          build-args: |
            PHP_BUILD_VERSION=${{ matrix.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}

  Build:
    name: Docker Image - ${{ matrix.name }} - ${{ matrix.version }}
    runs-on: ubuntu-latest
    needs: Base

    strategy:
      fail-fast: false
      matrix:
        name: [ 'php-fpm-alpine-api-pgsql', 'php-fpm-alpine-gui' ]
        version: [ '8.3' ]

    steps:
      # —— Setup Environment actions  ——————————————————————————————————————————————

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # —— Build release image  ——————————————————————————————————————————————
      - name: Build and push - PHP Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: ${{ matrix.name }}
          build-args: |
            PHP_BUILD_VERSION=${{ matrix.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY }}/IlluminatorCologne/${{ matrix.name }}:${{ matrix.version }}